-- Seed data: curated Swedish bostadsrätt/BRF buying tips plus example criteria and neighborhoods.
-- Idempotent: re-running skips rows that already exist (unique title/name).

INSERT OR IGNORE INTO tips (category, title, body, importance, source) VALUES
('brf_finance', 'Belåning per kvm: tumregler',
 'Föreningens lån delat med bostadsrättsytan (BOA) är det snabbaste måttet på BRF:ens skuldsättning. Under ~5 000 kr/kvm är lågt, 5 000–10 000 kr/kvm normalt, över ~12 000–15 000 kr/kvm högt (vanligt i nyproduktion). Jämför alltid med föreningens sparande och planerat underhåll – låg skuld men eftersatt underhåll är ingen fördel.',
 5, 'Vanliga branschtumregler (mäklare, banker, Bostadsrätterna)'),
('brf_finance', 'Din andel av föreningens skuld',
 'Räkna ut din "dolda" skuld: föreningens skuld per kvm × lägenhetens yta. 70 kvm i en förening med 12 000 kr/kvm i skuld innebär 840 000 kr som du indirekt betalar ränta på via avgiften. Lägg ihop med ditt eget bolån när du jämför lägenheter.',
 5, 'Grundläggande BRF-ekonomi'),
('brf_finance', 'Räntekänslighet och nyckeltal i årsredovisningen',
 'Sedan räkenskapsår som börjar 2023 ska BRF:er redovisa nyckeltal i förvaltningsberättelsen: årsavgift per kvm, skuldsättning per kvm, sparande per kvm, räntekänslighet och energikostnad per kvm. Räntekänsligheten visar hur mycket avgifterna måste höjas om räntan stiger 1 procentenhet – över ~10 % är en varningssignal.',
 5, 'BFNAR 2023:1 (Bokföringsnämnden)'),
('brf_finance', 'Sparande till underhåll',
 'Titta på nyckeltalet "sparande per kvm" (kassaflöde före avskrivningar och underhåll). Under ~150 kr/kvm/år är svagt för en äldre fastighet; över ~300 kr/kvm/år är starkt. Kontrollera att underhållsplanen finns, är uppdaterad och att avsättningen räcker till de planerade åtgärderna.',
 4, 'Branschpraxis; BFNAR 2023:1'),
('brf_finance', 'Röda flaggor i årsredovisningen',
 'Var uppmärksam på: kraftiga eller upprepade avgiftshöjningar, stora lån med kort räntebindning som förfaller snart, ökande skuld utan motsvarande investering, negativt kassaflöde flera år i rad (negativt resultat beror ofta bara på avskrivningar), revisorns anmärkningar eller ej godkänd revisor, samt stora tvister eller vattenskador under "väsentliga händelser".',
 5, 'Bostadsrättsföreningars årsredovisningar (ÅRL, K2/K3)'),
('brf_finance', 'Lokaler och andra intäkter',
 'Hyresintäkter från lokaler kan hålla nere avgiften, men kontrollera hur stor andel av intäkterna de står för, hyresgästernas kontraktslängd och vakansrisk. En förening som är beroende av en enda stor lokalhyresgäst är sårbar.',
 3, 'Branschpraxis'),
('renovation', 'Stambyte: ålder och kostnad',
 'Stammar håller ungefär 40–60 år. Byggt på 1950–70-talet utan genomfört stambyte? Räkna med ett stambyte inom kort – det kostar ofta flera hundra tusen kronor per lägenhet för föreningen, kan höja avgiften och innebär ofta 6–10 veckor utan fungerande badrum/kök. Fråga om relining är gjort i stället (billigare men kortare livslängd).',
 5, 'Branschpraxis (Svensk Försäkring, föreningsrådgivare)'),
('renovation', 'Tak, fasad, fönster och hiss',
 'Kontrollera i underhållsplanen när tak (ca 30–50 år), fasad, fönster (ca 30–40 år) och hiss senast åtgärdades. Stora åtgärder som är eftersatta blir antingen lån eller avgiftshöjningar – dvs. din kostnad.',
 4, 'Typiska livslängder i underhållsplaner'),
('legal', 'Tomträtt vs. äganderätt till marken',
 'Äger föreningen inte marken betalar den tomträttsavgäld till kommunen. Avgälden omregleras med 10–20 års intervall och kan höjas kraftigt (ibland flera gånger om). Ta reda på när nästa omreglering sker och om föreningen har möjlighet att friköpa tomten.',
 5, 'Jordabalken 13 kap.'),
('legal', 'Äkta vs. oäkta bostadsrättsförening',
 'En förening är "äkta" (privatbostadsföretag) om minst 60 % av fastighetens taxeringsvärde avser bostäder som används av medlemmarna. I en oäkta förening beskattas du på annat sätt – bl.a. förmånsbeskattning och sämre villkor vid försäljning (vinst beskattas som andel, uppskov ej möjligt). Står ofta i årsredovisningen.',
 4, 'Inkomstskattelagen 2 kap. 17 §'),
('legal', 'Stadgar: vem ansvarar för vad',
 'Läs föreningens stadgar: vad ingår i ditt inre underhållsansvar (badrum, fönster, balkong, ytterdörr), regler för andrahandsuthyrning, renovering och husdjur. Kontrollera också om föreningen tar ut överlåtelse- och pantsättningsavgift (max 2,5 % resp. 1 % av prisbasbeloppet).',
 3, 'Bostadsrättslagen (1991:614)'),
('legal', 'Köpekontraktet: medlemskap och friskrivningar',
 'Köpet blir ogiltigt om föreningen nekar dig medlemskap – kontrollera att kontraktet innehåller förbehåll om detta. Undvik långtgående friskrivningsklausuler, notera tillträdesdag och handpenning (oftast 10 %). Fråga säljaren om kända fel och om lägenheten har skulder till föreningen.',
 4, 'Bostadsrättslagen; Mäklarsamfundet'),
('viewing', 'Checklista vid visning',
 'Titta på badrummets ålder och skick (tätskikt, golvbrunn, fuktfläckar), elcentral (proppar vs. jordfelsbrytare), fönster, ventilation och vattentryck. Fråga när badrum och kök renoverades och om det finns intyg/kvitton. Gå även runt i trapphus, källare och tvättstuga – de visar hur föreningen sköts.',
 4, 'Besiktningsbranschen'),
('cost', 'Månadskostnad utöver avgiften',
 'Den verkliga månadskostnaden är ränta + amortering + avgift + drift: el, hemförsäkring med bostadsrättstillägg, bredband och ev. parkering. Kontrollera vad avgiften inkluderar (värme, vatten, bredband, el). Ränteavdraget är 30 % på räntekostnader upp till 100 000 kr/år.',
 4, 'Skatteverket'),
('cost', 'Bolånetak och amorteringskrav',
 'Bolånetaket begränsar lånet till en andel av bostadens värde (90 % från 1 april 2026, tidigare 85 %). Amorteringskravet: 2 % per år om belåningsgraden är över 70 %, 1 % om den är 50–70 %. Det skärpta kravet (extra 1 % vid lån över 4,5 gånger bruttoinkomsten) togs bort samtidigt. Kontrollera aktuella regler hos banken/Finansinspektionen.',
 5, 'Finansinspektionen'),
('negotiation', 'Budgivning är inte bindande',
 'I Sverige är bud inte juridiskt bindande förrän kontraktet är påskrivet – för varken köpare eller säljare. Ha lånelöfte klart, bestäm ert maxpris innan budgivningen, och läs årsredovisningen innan ni lägger bud. Ett lågt avgiftsläge kan vara ett argument, men en svag BRF är ett skäl att avstå.',
 4, 'Fastighetsmäklarinspektionen'),
('negotiation', 'Nyproduktion: ekonomisk plan och avgiftstrappa',
 'I nyproduktion är skulden per kvm ofta hög och avgiften kan vara artificiellt låg de första åren ("avgiftstrappa"). Läs den ekonomiska planen: vilken ränta har kalkylen antagit, hur höjs avgiften över tid, och vem står för osålda lägenheter?',
 4, 'Konsumentverket; Bostadsrättslagen'),
('brf_finance', 'Avgift per kvm som jämförelse',
 'Årsavgift per kvm gör föreningar jämförbara: ofta 600–900 kr/kvm/år i storstadsområden. En mycket låg avgift kan betyda att föreningen inte sparar tillräckligt; en hög avgift kan bero på hög skuld eller att mycket ingår (värme, vatten, bredband).',
 3, 'Branschpraxis');

INSERT OR IGNORE INTO neighborhoods (name, municipality, commute_minutes, avg_price_per_sqm, notes, rating) VALUES
('Hammarby Sjöstad', 'Stockholm', 25, 85000, 'Exempel – ersätt med egna siffror. Mycket nyare bestånd (1990–2010-tal), ofta högre BRF-skuld per kvm.', 4),
('Råsunda', 'Solna', 20, 75000, 'Exempel – ersätt med egna siffror. Mycket 1920–40-talsbestånd; kontrollera stambyten.', 4);

INSERT OR IGNORE INTO criteria (name, kind, field, operator, value, weight, notes) VALUES
('Minst 2 rum', 'hard', 'rooms', '>=', '2', 5, NULL),
('Maxpris 5 miljoner', 'hard', 'max_price', '<=', '5000000', 5, 'Exempel – justera efter lånelöfte.'),
('Avgift högst 5 000 kr/mån', 'soft', 'max_avgift', '<=', '5000', 4, NULL),
('Minst 55 kvm', 'soft', 'area_sqm', '>=', '55', 3, NULL),
('Föredragna områden', 'soft', 'area_name', 'in', '["Hammarby Sjöstad", "Råsunda"]', 3, NULL);
