-- Seed data: curated Swedish bostadsrätt/BRF buying tips plus example criteria and neighborhoods.
-- Idempotent: re-running skips rows that already exist (unique title/name).

INSERT OR IGNORE INTO tips (category, title, body, importance, source) VALUES
('brf_finance', 'Belåning per kvm: tumregler',
 'Föreningens lån delat med bostadsrättsytan (BOA) är det snabbaste måttet på BRF:ens skuldsättning. Under ~5 000 kr/kvm är lågt, 5 000–10 000 kr/kvm normalt, över ~12 000–15 000 kr/kvm högt (vanligt i nyproduktion). Jämför alltid med föreningens sparande och planerat underhåll – låg skuld men eftersatt underhåll är ingen fördel.',
 5, 'Vanliga branschtumregler (mäklare, banker, Bostadsrätterna)'),
('brf_finance', 'Din andel av föreningens skuld',
 'Räkna ut din "dolda" skuld: föreningens skuld per kvm × lägenhetens yta. 70 kvm i en förening med 12 000 kr/kvm i skuld innebär 840 000 kr som du indirekt betalar ränta på via avgiften. Lägg ihop med ditt eget bolån när du jämför lägenheter.',
 5, 'Grundläggande BRF-ekonomi'),
('brf_finance', 'Räntekänslighet och nyckeltal i årsredovisningen',
 'Sedan räkenskapsår som börjar 2023 ska BRF:er redovisa nyckeltal i förvaltningsberättelsen: årsavgift per kvm, skuldsättning per kvm, sparande per kvm, räntekänslighet och energikostnad per kvm. Räntekänsligheten visar hur mycket avgifterna måste höjas om räntan stiger 1 procentenhet – över ~10 % är en varningssignal.',
 5, 'BFNAR 2023:1 (Bokföringsnämnden)'),
('brf_finance', 'Sparande till underhåll',
 'Titta på nyckeltalet "sparande per kvm" (kassaflöde före avskrivningar och underhåll). Under ~150 kr/kvm/år är svagt för en äldre fastighet; över ~300 kr/kvm/år är starkt. Kontrollera att underhållsplanen finns, är uppdaterad och att avsättningen räcker till de planerade åtgärderna.',
 4, 'Branschpraxis; BFNAR 2023:1'),
('brf_finance', 'Röda flaggor i årsredovisningen',
 'Var uppmärksam på: kraftiga eller upprepade avgiftshöjningar, stora lån med kort räntebindning som förfaller snart, ökande skuld utan motsvarande investering, negativt kassaflöde flera år i rad (negativt resultat beror ofta bara på avskrivningar), revisorns anmärkningar eller ej godkänd revisor, samt stora tvister eller vattenskador under "väsentliga händelser".',
 5, 'Bostadsrättsföreningars årsredovisningar (ÅRL, K2/K3)'),
('brf_finance', 'Lokaler och andra intäkter',
 'Hyresintäkter från lokaler kan hålla nere avgiften, men kontrollera hur stor andel av intäkterna de står för, hyresgästernas kontraktslängd och vakansrisk. En förening som är beroende av en enda stor lokalhyresgäst är sårbar.',
 3, 'Branschpraxis'),
('renovation', 'Stambyte: ålder och kostnad',
 'Stammar håller ungefär 40–60 år. Byggt på 1950–70-talet utan genomfört stambyte? Räkna med ett stambyte inom kort – det kostar ofta flera hundra tusen kronor per lägenhet för föreningen, kan höja avgiften och innebär ofta 6–10 veckor utan fungerande badrum/kök. Fråga om relining är gjort i stället (billigare men kortare livslängd).',
 5, 'Branschpraxis (Svensk Försäkring, föreningsrådgivare)'),
('renovation', 'Tak, fasad, fönster och hiss',
 'Kontrollera i underhållsplanen när tak (ca 30–50 år), fasad, fönster (ca 30–40 år) och hiss senast åtgärdades. Stora åtgärder som är eftersatta blir antingen lån eller avgiftshöjningar – dvs. din kostnad.',
 4, 'Typiska livslängder i underhållsplaner'),
('legal', 'Tomträtt vs. äganderätt till marken',
 'Med tomträtt hyr föreningen marken och betalar tomträttsavgäld (ofta till kommunen). Med äganderätt äger föreningen marken och ingen tomträttsavgäld tillkommer. Vid tomträtt omregleras avgälden med 10–20 års intervall och kan höjas kraftigt. Ta reda på vilket som gäller i årsredovisningen, när nästa omreglering sker och om friköp är möjligt.',
 5, 'Jordabalken 13 kap.'),
('legal', 'Äkta vs. oäkta bostadsrättsförening',
 'En förening är "äkta" (privatbostadsföretag) om minst 60 % av fastighetens taxeringsvärde avser bostäder som används av medlemmarna. I en oäkta förening beskattas du på annat sätt – bl.a. förmånsbeskattning och sämre villkor vid försäljning (vinst beskattas som andel, uppskov ej möjligt). Står ofta i årsredovisningen.',
 4, 'Inkomstskattelagen 2 kap. 17 §'),
('legal', 'Stadgar: vem ansvarar för vad',
 'Läs föreningens stadgar: vad ingår i ditt inre underhållsansvar (badrum, fönster, balkong, ytterdörr), regler för andrahandsuthyrning, renovering och husdjur. Kontrollera också om föreningen tar ut överlåtelse- och pantsättningsavgift (max 2,5 % resp. 1 % av prisbasbeloppet).',
 3, 'Bostadsrättslagen (1991:614)'),
('legal', 'Köpekontraktet: medlemskap och friskrivningar',
 'Köpet blir ogiltigt om föreningen nekar dig medlemskap – kontrollera att kontraktet innehåller förbehåll om detta. Undvik långtgående friskrivningsklausuler, notera tillträdesdag och handpenning (oftast 10 %). Fråga säljaren om kända fel och om lägenheten har skulder till föreningen.',
 4, 'Bostadsrättslagen; Mäklarsamfundet'),
('viewing', 'Checklista vid visning',
 'Titta på badrummets ålder och skick (tätskikt, golvbrunn, fuktfläckar), elcentral (proppar vs. jordfelsbrytare), fönster, ventilation och vattentryck. Fråga när badrum och kök renoverades och om det finns intyg/kvitton. Gå även runt i trapphus, källare och tvättstuga – de visar hur föreningen sköts.',
 4, 'Besiktningsbranschen'),
('cost', 'Månadskostnad utöver avgiften',
 'Den verkliga månadskostnaden är ränta + amortering + avgift + drift: el, hemförsäkring med bostadsrättstillägg, bredband och ev. parkering. Kontrollera vad avgiften inkluderar (värme, vatten, bredband, el). Ränteavdraget är 30 % på räntekostnader upp till 100 000 kr/år.',
 4, 'Skatteverket'),
('cost', 'Bolånetak och amorteringskrav',
 'Bolånetaket begränsar lånet till en andel av bostadens värde (90 % från 1 april 2026, tidigare 85 %). Amorteringskravet: 2 % per år om belåningsgraden är över 70 %, 1 % om den är 50–70 %. Det skärpta kravet (extra 1 % vid lån över 4,5 gånger bruttoinkomsten) togs bort samtidigt. Kontrollera aktuella regler hos banken/Finansinspektionen.',
 5, 'Finansinspektionen'),
('negotiation', 'Budgivning är inte bindande',
 'I Sverige är bud inte juridiskt bindande förrän kontraktet är påskrivet – för varken köpare eller säljare. Ha lånelöfte klart, bestäm ert maxpris innan budgivningen, och läs årsredovisningen innan ni lägger bud. Ett lågt avgiftsläge kan vara ett argument, men en svag BRF är ett skäl att avstå.',
 4, 'Fastighetsmäklarinspektionen'),
('negotiation', 'Nyproduktion: ekonomisk plan och avgiftstrappa',
 'I nyproduktion är skulden per kvm ofta hög och avgiften kan vara artificiellt låg de första åren ("avgiftstrappa"). Läs den ekonomiska planen: vilken ränta har kalkylen antagit, hur höjs avgiften över tid, och vem står för osålda lägenheter?',
 4, 'Konsumentverket; Bostadsrättslagen'),
('brf_finance', 'Avgift per kvm som jämförelse',
 'Årsavgift per kvm gör föreningar jämförbara: ofta 600–900 kr/kvm/år i storstadsområden. En mycket låg avgift kan betyda att föreningen inte sparar tillräckligt; en hög avgift kan bero på hög skuld eller att mycket ingår (värme, vatten, bredband).',
 3, 'Branschpraxis'),
('legal', 'Äganderätt till marken – inte samma som tomträtt',
 'Äganderätt betyder att föreningen äger marken; tomträtt betyder att marken hyrs och avgäld betalas. I årsredovisningen: not om tomträtt och eventuell tomträttsavgäld. Fråga uttryckligen: "Har föreningen äganderätt eller tomträtt till marken?" – inte bara om föreningen "äger fastigheten".',
 5, 'docs/brf-evaluation-guide.md'),
('legal', 'Hyresrätter i samma förening',
 'Vissa föreningar har både bostadsrätter och hyresrätter (eller många lokaler). Det kan påverka underhållsprioritering och avgiftsnivå. Räkna antal hyresrätter, läs stadgar och fråga styrelsen hur intäkterna används. Enbart bostadsrätter är enklare att förstå ekonomiskt.',
 4, 'docs/brf-evaluation-guide.md'),
('brf_finance', 'Kassa mot föreningsskuld',
 'Jämför kassa/bank med total skuld. En kassa under cirka 2 % av skulden ger liten buffert om räntan stiger. Som tumregel: minst ~25 000 kr kassa per lägenhet är acceptabelt; över ~75 000 kr/lgh är starkt – men äldre hus med stora planerade projekt kan behöva mer.',
 4, 'docs/brf-evaluation-guide.md'),
('renovation', 'Fönsterbyte i 60–70-tals hus',
 'Originalfönster från byggåret är ofta dåliga för energi och ljud. Ett fönsterbyte för hela huset är dyrt och kan planeras i underhållsplanen. Fråga om det är gjort, pågår eller budgeterat – och om det finansieras med lån eller avgiftshöjning.',
 4, 'docs/brf-evaluation-guide.md'),
('brf_finance', 'Föreningsstorlek: antal lägenheter',
 'Under cirka 15 lägenheter blir varje större åtgärd (tak, stambyte) dyr per hushåll. 15–80 lägenheter är ofta en lagom storlek för förvaltning. I mycket stora föreningar: kontrollera att underhållsplanen är uppdelad per byggnad.',
 3, 'docs/brf-evaluation-guide.md'),
('brf_finance', 'Förvaltare: HSB, Riksbyggen och andra',
 'Årsredovisningen visar vem som förvaltar (HSB, Riksbyggen, SBC, Nabo, etc.). Etablerad förvaltning innebär ofta bättre rutiner och dokumentation – men läs ändå revisorns text och skuldsättning. Egen förvaltning kan fungera bra i små föreningar om styrelsen är aktiv.',
 3, 'docs/brf-evaluation-guide.md'),
('renovation', 'Planerat vs oförutsägt underhåll',
 'Skillnad på planerade åtgärder i underhållsplanen (tak 2030, fasad 2028) och akuta skador (läckage, hiss haveri). Planerat kan ni budgetera för; oförutsägt utan kassa leder till snabba lån och avgiftshöjningar. Fråga styrelsen om oförutsedda kostnader senaste fem åren.',
 4, 'docs/brf-evaluation-guide.md');

-- Erik & Jenny — neighborhoods (commute to Odenplan TBD unless noted)
INSERT OR IGNORE INTO neighborhoods (name, municipality, commute_minutes, avg_price_per_sqm, notes, rating) VALUES
('Sickla', 'Nacka', NULL, NULL, 'Pendlings tid till Odenplan TBD. Barnvänlighet, trygghet och service — verifiera per objekt.', 3),
('Järla', 'Nacka', NULL, NULL, 'Pendlings tid till Odenplan TBD.', 3),
('Finntorp', 'Nacka', NULL, NULL, 'Pendlings tid till Odenplan TBD.', 3),
('Järlaberg', 'Nacka', NULL, NULL, 'Pendlings tid till Odenplan TBD.', 3),
('Nacka Forum', 'Nacka', NULL, NULL, 'Pendlings tid till Odenplan TBD.', 3),
('Nacka Strand', 'Nacka', NULL, NULL, 'Pendlings tid till Odenplan TBD. Nära vatten.', 4),
('Henriksdal', 'Nacka', NULL, NULL, 'Pendlings tid till Odenplan TBD.', 3),
('Hammarbyhöjden', 'Stockholm', NULL, NULL, 'Pendlings tid till Odenplan TBD.', 3),
('Björkhagen', 'Stockholm', NULL, NULL, 'Pendlings tid till Odenplan TBD.', 3),
('Hammarby Sjöstad', 'Stockholm', NULL, NULL, 'Pendlings tid till Odenplan TBD. Nyare bestånd, ofta högre BRF-skuld per kvm.', 4),
('Kärrtorp', 'Stockholm', NULL, NULL, 'Pendlings tid till Odenplan TBD.', 3),
('Blåsut', 'Stockholm', NULL, NULL, 'Pendlings tid till Odenplan TBD.', 3),
('Enskede', 'Stockholm', NULL, NULL, 'Pendlings tid till Odenplan TBD.', 3),
('Årsta', 'Stockholm', NULL, NULL, 'Pendlings tid till Odenplan TBD.', 3),
('Johanneshov', 'Stockholm', NULL, NULL, 'Pendlings tid till Odenplan TBD.', 3),
('Södermalm', 'Stockholm', NULL, NULL, 'Pendlings tid till Odenplan TBD. Brett område — bedöm delområde per objekt.', 4),
('Liljeholmskajen', 'Stockholm', NULL, NULL, 'Pendlings tid till Odenplan TBD.', 3),
('Årstaberg', 'Stockholm', NULL, NULL, 'Pendlings tid till Odenplan TBD.', 3),
('Aspudden', 'Stockholm', NULL, NULL, 'Pendlings tid till Odenplan TBD.', 3),
('Alvik', 'Stockholm', NULL, NULL, 'Pendlings tid till Odenplan TBD.', 3),
('Bromma', 'Stockholm', NULL, NULL, 'Pendlings tid till Odenplan TBD.', 3),
('Solna', 'Solna', NULL, NULL, 'Pendlings tid till Odenplan TBD. Kommun/område — specificera vid sökning.', 3),
('Sundbyberg', 'Sundbyberg', NULL, NULL, 'Pendlings tid till Odenplan TBD.', 3),
('Annedal', 'Stockholm', NULL, NULL, 'Pendlings tid till Odenplan TBD.', 3),
('Mariehäll', 'Sundbyberg', NULL, NULL, 'Pendlings tid till Odenplan TBD.', 3);

-- Erik & Jenny — buying criteria (see docs/buying-criteria.md)
INSERT OR IGNORE INTO criteria (name, kind, field, operator, value, weight, notes) VALUES
('Minst 65 kvm', 'hard', 'area_sqm', '>=', '65', 5, NULL),
('Minst 3 rok', 'hard', 'rooms', '>=', '3', 5, NULL),
('Maxpris 3,5 MSEK', 'hard', 'price', '<=', '3500000', 5, 'Flexibel budget — sparar fortfarande; möjligt familjelån från anhöriga.'),
('Avgift högst 8 000 kr/mån', 'hard', 'monthly_fee', '<=', '8000', 5, NULL),
('Pendling till Odenplan', 'hard', 'commute_odenplan_min', '<=', '40', 5, 'Kollektivtrafik; verifiera per adress.'),
('Balkong eller uteplats', 'hard', 'outdoor_space', 'in', '["balcony", "patio"]', 5, 'Minst en av balkong eller liten uteplats.'),
('Diskmaskin', 'hard', 'has_dishwasher', '=', 'true', 5, NULL),
('Tvättmaskin', 'hard', 'has_washing_machine', '=', 'true', 5, 'I lägenheten eller tydligt tillåtet.'),
('Inte källarvåning', 'hard', 'is_basement', '=', 'false', 5, 'Mycket dagsljus; undvik källarplan.'),
('Externt förvaring möjligt', 'soft', 'external_storage_possible', '=', 'true', 4, 'T.ex. föreningsförråd eller hyreslås — kontrollera med BRF.'),
('Föredragna områden', 'soft', 'area_name', 'in', '["Sickla", "Järla", "Finntorp", "Järlaberg", "Nacka Forum", "Nacka Strand", "Henriksdal", "Hammarbyhöjden", "Björkhagen", "Hammarby Sjöstad", "Kärrtorp", "Blåsut", "Enskede", "Årsta", "Johanneshov", "Södermalm", "Liljeholmskajen", "Årstaberg", "Aspudden", "Alvik", "Bromma", "Solna", "Sundbyberg", "Annedal", "Mariehäll"]', 4, NULL),
('Barnvänligt område', 'soft', 'area_child_friendly', '=', 'true', 4, 'Bedöm utifrån kvarter, lekplatser och upplevd miljö.'),
('Trygghetsintryck', 'soft', 'area_safety_reputation', '=', 'true', 5, 'Undvik områden med dåligt rykte kring gäng/skottlossningar — egen research krävs.'),
('Förskola nära', 'soft', 'area_kindergarten_nearby', '=', 'true', 4, NULL),
('Matbutik nära', 'soft', 'area_grocery_nearby', '=', 'true', 3, NULL),
('Nära vatten och natur', 'soft', 'area_water_nature_access', '=', 'true', 4, 'Promenadavstånd eller kort resa till grönområden/vatten.'),
('Liten egen bakgård', 'soft', 'has_small_backyard', '=', 'true', 2, 'Sällsynt i BRF — bonus om det finns.'),
('Minst 80 kvm', 'soft', 'area_sqm', '>=', '80', 3, 'Över minimikravet 65 kvm.'),
('Uteplats/balkong mot sydost', 'soft', 'outdoor_facing', 'in', '["SE", "south_east"]', 3, 'Sydostligt ljus på balkong/uteplats.'),
('Stort kök', 'soft', 'has_large_kitchen', '=', 'true', 3, NULL),
('Öppen planlösning vardagsrum/kök', 'soft', 'open_plan_living_kitchen', '=', 'true', 3, NULL),
('Altandörr från vardagsrum/kök', 'soft', 'patio_door_from_living', '=', 'true', 4, 'Inte från sovrum.'),
('Två badrum', 'soft', 'bathroom_count', '>=', '2', 3, NULL),
('Tvättutrymme i badrum', 'soft', 'laundry_space_in_bathroom', '=', 'true', 2, 'Plats för tvätt i minst ett badrum.'),
('Värdlägenhet i BRF', 'soft', 'brf_guest_apartment', '=', 'true', 2, 'Gästlägenhet i föreningen.'),
('Nära bad-/simvatten', 'soft', 'near_swimming_water', '=', 'true', 3, 'Badplats eller simmöjlighet i närheten.');
